name: CREATE CHROME EXTENSION

on:
  push:
    branches:
      - main

jobs:
  create_chrome_extension:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
      working-directory: ./app/python/  

    - name: Generate Template
      run: |
        
        python generate_block_page.py
      working-directory: ./app/python/

    - name: Commit changes
      run: |
        cp ./python/rules.json ./extensions/rules.json
        tree
      working-directory: ./app/ 

    - name: Create Extension
      run: |
        # Copier les fichiers nécessaires pour l'extension dans le répertoire "extension_chrome_files"
        mkdir -p extension_chrome_files
        cp ./chrome/manifest.json extension_chrome_files/
        cp ./icon.png extension_chrome_files/
        cp ./rules.json extension_chrome_files/rules.json
      working-directory: ./app/extensions 

    - name: Zip Extension
      run: |
        zip -r extension.zip .
      working-directory: ./app/extensions/extension_chrome_files

    - name: Upload Extension
      uses: actions/upload-artifact@v2
      with:
        name: chrome-extension
        path: ./app/extensions/extension_chrome_files/extension.zip